
import { ProjectInfo } from "./types";

// Mock data for projects
export const mockProjects: ProjectInfo[] = [
  {
    id: "1",
    name: "Lagos-Ibadan Expressway Rehabilitation",
    description: "Complete rehabilitation of the Lagos-Ibadan expressway to improve transportation infrastructure",
    status: "In Progress",
    budget: 167000000000,
    spent: 89000000000,
    location: "Lagos/Oyo States",
    startDate: "2018-03-15",
    endDate: "2023-12-31",
    ministry: "Ministry of Works and Housing",
    contractor: "Julius Berger & RCC Nigeria Limited"
  },
  {
    id: "2",
    name: "Abuja Light Rail Project",
    description: "Construction of a light rail system to improve public transportation in the FCT",
    status: "Completed",
    budget: 45000000000,
    spent: 52000000000,
    location: "Federal Capital Territory",
    startDate: "2015-07-12",
    endDate: "2022-05-20",
    ministry: "FCT Administration",
    contractor: "CCECC Nigeria Limited"
  },
  {
    id: "3",
    name: "Primary Healthcare Centers Renovation",
    description: "Renovation and equipping of 10,000 primary healthcare centers across Nigeria",
    status: "Delayed",
    budget: 55000000000,
    spent: 23000000000,
    location: "Nationwide",
    startDate: "2020-01-10",
    endDate: "2023-01-10",
    ministry: "Ministry of Health",
    contractor: "Multiple Contractors"
  },
  {
    id: "4",
    name: "Second Niger Bridge Construction",
    description: "Construction of a second bridge over the River Niger between Asaba and Onitsha",
    status: "Completed",
    budget: 206870000000,
    spent: 210000000000,
    location: "Delta/Anambra States",
    startDate: "2017-08-15",
    endDate: "2022-10-25",
    ministry: "Ministry of Works and Housing",
    contractor: "Julius Berger Nigeria PLC"
  },
  {
    id: "5",
    name: "Mambilla Hydroelectric Power Project",
    description: "Construction of a 3,050 MW hydroelectric power plant on the Mambilla Plateau",
    status: "Planning Phase",
    budget: 5800000000000,
    spent: 200000000000,
    location: "Taraba State",
    startDate: "2021-06-01",
    endDate: "2030-12-31",
    ministry: "Ministry of Power",
    contractor: "China Civil Engineering Construction Corporation"
  },
  {
    id: "6",
    name: "Lekki Deep Sea Port Development",
    description: "Development of a deep sea port in the Lagos Free Trade Zone",
    status: "In Progress",
    budget: 398000000000,
    spent: 290000000000,
    location: "Lagos State",
    startDate: "2019-03-29",
    endDate: "2024-09-30",
    ministry: "Ministry of Transportation",
    contractor: "China Harbour Engineering Company"
  },
  {
    id: "7",
    name: "Kaduna-Kano Standard Gauge Railway",
    description: "Construction of a standard gauge railway line connecting Kaduna and Kano cities",
    status: "In Progress",
    budget: 1200000000000,
    spent: 450000000000,
    location: "Kaduna/Kano States",
    startDate: "2021-07-15",
    endDate: "2025-12-30",
    ministry: "Ministry of Transportation",
    contractor: "China Civil Engineering Construction Corporation"
  },
  {
    id: "8",
    name: "National Library Headquarters Construction",
    description: "Construction of the new National Library headquarters in Abuja",
    status: "Delayed",
    budget: 78000000000,
    spent: 35000000000,
    location: "Federal Capital Territory",
    startDate: "2006-12-10",
    endDate: "2023-05-15",
    ministry: "Ministry of Education",
    contractor: "Reynolds Construction Company"
  },
  {
    id: "9",
    name: "Ajaokuta Steel Plant Revitalization",
    description: "Rehabilitation and modernization of the Ajaokuta Steel Complex",
    status: "Planning Phase",
    budget: 400000000000,
    spent: 15000000000,
    location: "Kogi State",
    startDate: "2022-09-01",
    endDate: "2027-08-31",
    ministry: "Ministry of Mines and Steel Development",
    contractor: "Pending Selection"
  },
  {
    id: "10",
    name: "Ogoni Land Cleanup Project",
    description: "Environmental remediation and cleanup of oil pollution in Ogoni Land",
    status: "In Progress",
    budget: 190000000000,
    spent: 85000000000,
    location: "Rivers State",
    startDate: "2019-01-20",
    endDate: "2026-12-31",
    ministry: "Ministry of Environment",
    contractor: "Multiple International & Local Contractors"
  },
  {
    id: "11",
    name: "Calabar-Lagos Coastal Highway",
    description: "Construction of a coastal highway connecting Calabar to Lagos",
    status: "Planning Phase",
    budget: 2500000000000,
    spent: 120000000000,
    location: "Multiple Coastal States",
    startDate: "2023-02-01",
    endDate: "2032-12-31",
    ministry: "Ministry of Works and Housing",
    contractor: "Pending Final Selection"
  },
  {
    id: "12",
    name: "Zungeru Hydroelectric Power Project",
    description: "Construction of a 700 MW hydroelectric power plant in Niger State",
    status: "Completed",
    budget: 162900000000,
    spent: 175000000000,
    location: "Niger State",
    startDate: "2013-05-28",
    endDate: "2022-03-15",
    ministry: "Ministry of Power",
    contractor: "CNEEC-Sinohydro Consortium"
  },
  {
    id: "13",
    name: "Port Harcourt Refinery Rehabilitation",
    description: "Complete overhaul and modernization of the Port Harcourt Refinery",
    status: "In Progress",
    budget: 591200000000,
    spent: 310000000000,
    location: "Rivers State",
    startDate: "2021-04-06",
    endDate: "2024-04-05",
    ministry: "Ministry of Petroleum Resources",
    contractor: "Tecnimont SPA"
  },
  {
    id: "14",
    name: "Abuja-Kaduna-Kano Gas Pipeline",
    description: "Construction of a gas pipeline from Abuja through Kaduna to Kano",
    status: "In Progress",
    budget: 290000000000,
    spent: 142000000000,
    location: "FCT/Kaduna/Kano",
    startDate: "2020-06-30",
    endDate: "2023-12-31",
    ministry: "Ministry of Petroleum Resources",
    contractor: "Oilserv Limited"
  },
  {
    id: "15",
    name: "Enugu Airport Renovation",
    description: "Comprehensive renovation of the Akanu Ibiam International Airport in Enugu",
    status: "Completed",
    budget: 10000000000,
    spent: 12500000000,
    location: "Enugu State",
    startDate: "2019-08-24",
    endDate: "2020-08-30",
    ministry: "Ministry of Aviation",
    contractor: "PW Nigeria Limited"
  }
];
